name: fitlinkr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

  fonts:
    - family: Jura
      fonts:
        - asset: fonts/Jura-VariableFont_wght.ttf

    - family: IstokWeb
      fonts:
        - asset: fonts/IstokWeb-Bold.ttf

    - family: Inter
      fonts:
        - asset: fonts/Inter-VariableFont_opsz,wght.ttf
